### PR TITLE
Ignore drag gestures if no actions are provided

### PR DESCRIPTION
**Pull request by NaikSoftware**
Use case: chat in the tab - with reply by swipe from one edge and switch tab by swipe from other edge. At the moment horizontal drag in both axis intercepted by GestureDetector even if trailing or  leading actions are empty.

### CODE REVIEW

**Comment by luckysmg** [comment]
Thx your PR,I will check it as soon as I can 😀

**Comment by luckysmg** [comment]
The code looks good to me .But for the sake of reliability,I will check your branch and test manually on weekends(I m busy now 😫).And If there is no problem ,I will reply you and merge this PR before next week.

**Comment by luckysmg** [comment]
Hi @NaikSoftware ,I have tested your code ,No problem,But it will be better if you make `DirectionDependentDragGestureRecognizer` private. You can make it called `_DirectionDependentDragGestureRecognizer`😊😊

**Comment by NaikSoftware** [comment]
@luckysmg done

**Comment by luckysmg** [comment]
Thx your PR!😀😀

**Pull request merged**
